# Generated by Django 5.1.7 on 2025-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
